project:
  type: website

website:
  title: "QMEL Forecasts"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: fall_2025/
        text: Fall 2025 Workshop
      - href: projects/
        text: projects


format:
  html:
    theme: cosmo
    toc: true
